apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangoaksapp
  labels:
    app: djangoaksapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: djangoaksapp
  template:
    metadata:
      labels:
        app: djangoaksapp
    spec:
      containers:
      - name: djangoaksapp
        image: djangoappacr-cge6gyhjgydubtef.azurecr.io/djangoaksapp
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "False"
        - name: ALLOWED_HOSTS
          value: "*"  # Configure this properly for production
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: djangoappacrf415-auth
