apiVersion: v1
kind: Service
metadata:
  name: djangoaksapp-service
  labels:
    app: djangoaksapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: djangoaksapp
