apiVersion: v1
kind: Service
metadata:
    name: sahilcmdsnakegameazuredevopsaks
spec:
    type: LoadBalancer
    ports:
    - port: 8000 
    selector:
        app: sahilcmdsnakegameazuredevopsaks